-- 로그 테이블 먼저 생성
CREATE TABLE enroll_log (
                            log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            s_id VARCHAR2(20),
                            c_id_no VARCHAR2(20),
                            log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 트리거 생성
CREATE OR REPLACE TRIGGER trg_log_enroll
    AFTER INSERT ON enroll
    FOR EACH ROW
BEGIN
    INSERT INTO enroll_log(s_id, c_id_no)
    VALUES (:NEW.s_id, :NEW.c_id_no);
END;
/