--전달예정(8:28분 전달)

DROP TABLE enroll_log;
-- ✅ 로그 테이블 생성
CREATE TABLE enroll_log (
                            log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, -- 자동 증가 ID
                            s_id VARCHAR2(20),                -- 학생 학번
                            c_id_no VARCHAR2(20),             -- 과목 번호
                            e_year NUMBER,                    -- 수강 연도
                            e_semester NUMBER,                -- 수강 학기
                            log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- 로그 시간
);

-- ✅ 트리거 생성: 수강 신청 INSERT 시 로그 자동 기록
CREATE OR REPLACE TRIGGER trg_log_enroll
    AFTER INSERT ON enroll
    FOR EACH ROW
BEGIN
    INSERT INTO enroll_log (s_id, c_id_no, e_year, e_semester)
    VALUES (:NEW.s_id, :NEW.c_id_no, :NEW.e_year, :NEW.e_semester);
END;
/