-- Courses 테이블
CREATE TABLE Courses (
    c_id_no VARCHAR2(10) PRIMARY KEY,
    c_id VARCHAR2(50) NOT NULL,
    c_unit NUMBER NOT NULL,
    c_major VARCHAR2(30) NOT NULL
);

-- Professors 테이블
CREATE TABLE Professors (
    p_id VARCHAR2(10) PRIMARY KEY,
    p_name VARCHAR2(30) NOT NULL,
    p_major VARCHAR2(30)
);

-- Students 테이블
CREATE TABLE Students (
    s_id VARCHAR2(10) PRIMARY KEY,
    s_name VARCHAR2(30) NOT NULL,
    s_major VARCHAR2(30),
    s_grade NUMBER NOT NULL,
    s_semester NUMBER NOT NULL,
    s_status VARCHAR2(10) NOT NULL,
    s_pwd VARCHAR2(30) NOT NULL,
    s_address VARCHAR2(100),
    s_phone VARCHAR2(15),
    s_email VARCHAR2(50),
    s_bank VARCHAR2(50),
    s_dual_major VARCHAR2(30)
);

-- Sections 테이블
CREATE TABLE Sections (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    c_id_no VARCHAR2(10) NOT NULL,
    c_id VARCHAR2(50) NOT NULL,
    se_year NUMBER NOT NULL,
    se_semester NUMBER NOT NULL,
    se_section NUMBER NOT NULL,
    se_time VARCHAR2(20) NOT NULL,
    se_capacity NUMBER NOT NULL,
    p_id VARCHAR2(10) NOT NULL,
    se_classroom VARCHAR2(30),
    CONSTRAINT fk_sections_course FOREIGN KEY (c_id_no) REFERENCES Courses(c_id_no),
    CONSTRAINT fk_sections_professor FOREIGN KEY (p_id) REFERENCES Professors(p_id),
    CONSTRAINT uq_sections_unique UNIQUE (c_id_no, se_year, se_semester, se_section)
);

-- Enroll 테이블
CREATE TABLE Enroll (
    e_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    s_id VARCHAR2(10) NOT NULL,
    e_year NUMBER NOT NULL,
    e_semester NUMBER NOT NULL,
    c_id_no VARCHAR2(10) NOT NULL,
    e_section NUMBER NOT NULL,
    c_id VARCHAR2(50) NOT NULL,
    e_score FLOAT,
    CONSTRAINT fk_enroll_student FOREIGN KEY (s_id) REFERENCES Students(s_id),
    CONSTRAINT fk_enroll_course FOREIGN KEY (c_id_no) REFERENCES Courses(c_id_no),
    CONSTRAINT uq_enroll_student_course UNIQUE (s_id, c_id_no)
);